# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: Azure PipeLine FE

pr: none
trigger:
  branches:
    include:
    - main 
  paths:
    include: 
      - FE/*
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    CI=false
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: ./FE

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './FE/dist/fe'
    ArtifactName: 'production'
    publishLocation: 'Container'

# - script: |
#     CI=false
#     npm install
#     npm run build
#   displayName: 'npm install and build'
#   workingDirectory: ./FE

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: './FE/dist/fe'
#     ArtifactName: 'stageing'
#     publishLocation: 'Container'


#For Staging later on VVV
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: './FE/dist/fe'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'


# - script: |
#     CI=false
#     npm install
#     npm run build
#   displayName: 'npm install and build'
#   workingDirectory: ./FE