# Node.js with Angular
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: Azure PipeLine FE

pr: none
trigger:
  branches:
    include:
    - main 
  paths:
    include: 
      - FE/*
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: replacetokens@5
  inputs:
    rootDirectory: './FE/src/app'
    targetFiles: '**/environments/*.ts'
    encoding: 'auto'
    tokenPattern: 'default'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- script: |
    CI=false
    npm install
    #npm run build --configuration production
    #below need to test
    ng build --configuration production
  displayName: 'npm install and build'
  workingDirectory: ./FE

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './FE/dist/FE'
    ArtifactName: 'production'
    publishLocation: 'Container'

- script: |
    CI=false
    npm install
    ng build --configuration staging
  displayName: 'npm install and build'
  workingDirectory: ./FE

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './FE/dist/FE'
    ArtifactName: 'staging'
    publishLocation: 'Container'